export default defineEventHandler(async (event) => {
    const query = getQuery(event)
    const title = query.title || 'Unknown Task'

    const encoder = new TextEncoder()
    const stream = new ReadableStream({
        async start(controller) {
            const chunks = [
                `# PRD: ${title}\n\n`,
                "## 1. Objective\nAutomate the core workflow for this feature.\n\n",
                "## 2. User Stories\n- As a user, I want to see results instantly.\n- As a system, I should handle errors gracefully.\n\n",
                "## 3. Technical Specs\n- Frontend: Vue 3 / Nuxt 3\n- Backend: Prisma / SQLite\n\n",
                "--- \n*Generated by AI Assistant*"
            ]

            for (const chunk of chunks) {
                // Simulate streaming delay
                await new Promise(r => setTimeout(r, 200))
                controller.enqueue(encoder.encode(chunk))
            }
            controller.close()
        }
    })

    return sendStream(event, stream)
})
